### ISSUE TITLE
Profile names aren´t correct

### ISSUE THREAD

**Issue by jeregon1** [cspotcode/Flow.Launcher.Plugin.EdgeWorkspaces#2]
My Edge profiles don't have these names, these seem to be the default profile names.

![image](https://github.com/user-attachments/assets/76e8a04e-de48-445c-953e-8b0fb3806940)

Do you need further info? Thanks for the plugin!

**Comment by cspotcode** [comment]
Hmm, do you know where the correct profile names are stored?  The current logic was copied from the corresponding PowerToys Run plugin. IIRC, profile names come from the name of the directory in "%LOCALAPPDATA%/Microsoft/Edge/User Data/". Perhaps the real name should be read from a JSON file somewhere?

**Comment by cspotcode** [comment]
@jeregon1 any update on this?

**Comment by jeregon1** [comment]
Nope, I just named the workspaces differently, it's not that inconvenient
